name: taxi_app
description: Aplicación para gestionar colas de taxis
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  flutter_local_notifications: ^17.2.4
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.1
  reorderable_grid_view: ^2.2.8
  crypto: ^3.0.3
  google_maps_flutter: ^2.6.0
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 